services:
  web:
    container_name: node
#    image: ${REGISTRY_USER}/venus:${IMAGE_TAG:-latest}
    image: angelstarart/venus:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    depends_on:
      - db
      - certbot
    networks:
      - web-db
    mem_limit: 450m
    cpus: "1.0"

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    mem_limit: 64m
    cpus: "0.25"

  db:
    container_name: mongodb
    image: mongo:8.3.11
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$USER
      - MONGO_INITDB_ROOT_PASSWORD=$PASS
      - MONGO_INITDB_DATABASE=$USER
    ports:
      - '27017:27017'
    expose:
      - 27017
    volumes:
      - mongodb:/data/db
#       - ./init-mongodb:/docker-entrypoint-initdb.d
    command:
      - --auth
    networks:
      - web-db
    mem_limit: 256m
    cpus: "0.75"

volumes:
  mongodb:
  certbot-www:
  certbot-conf:

networks:
  web-db:
