services:
  os:
    container_name: almaLinux
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: os
      args:
        user: $USER
        pass: $PASS
    privileged: true
    restart: always
    env_file: ./.env
    ports:
#      - "53:53"
      - "8008:8008"
    depends_on:
      - web
    networks:
      - os-web

  web:
    container_name: node
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: web
      args:
        user: $USER
        pass: $PASS
    privileged: true
    restart: always
    env_file: ./.env
    ports:
      - "3010:3000"
    volumes:
      -  ./packages:/usr/src/app/packages
    depends_on:
      - db
    networks:
      - web-db
      - os-web

  db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$USER
      - MONGO_INITDB_ROOT_PASSWORD=$PASS
      - MONGO_INITDB_DATABASE=$USER
    ports:
      - '6000:27017'
    expose:
      - 27017
    volumes:
       - mongodb:/data/db
#       - ./init-mongodb:/docker-entrypoint-initdb.d
    command: [--auth]
    networks:
      - web-db

volumes:
  mongodb:
  redis:

networks:
  web-db:
  os-web:
